# theme = "catppuccin_frappe"
# theme = "fleet_dark"
theme = "rose_pine_moon"

[editor]
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
rulers = [120]
idle-timeout = 50
line-number = "relative"
undercurl = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-type", "total-line-numbers", "file-encoding"]
center = ["file-name"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
mode.normal = "RW"
mode.insert = "**"
mode.select = "SL"

[editor.whitespace.render]
nbsp = "all"

[editor.whitespace.characters]
nbsp = "⍽"
